FROM python:3.10.2 as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

RUN groupadd -r --gid 10001 devs
RUN useradd -r -g devs -u 20008 user
RUN chown -R user:devs /usr/src/app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip setuptools

COPY requirements*.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-all.txt


FROM python:3.10.2
COPY --from=builder /opt/venv /opt/venv

WORKDIR /usr/src/app
ENV PATH="/opt/venv/bin:$PATH"

COPY . .
