FROM python:3.10.2-slim
RUN pip install --upgrade pip setuptools

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

WORKDIR /usr/src/app
COPY . .
