FROM python:3.10.2-slim

WORKDIR /usr/src/app

RUN groupadd -r --gid 10001 devs
RUN useradd -r -g devs -u 20008 user
RUN chown -R user:devs /usr/src/app

RUN pip install --upgrade pip setuptools

COPY requirements*.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-all.txt

WORKDIR /usr/src/app
COPY . .
